In [1]:
import numpy as np
from scipy.spatial.distance import pdist, cdist, squareform

In [2]:
N = 1200
np.random.seed(2024)
X = np.random.uniform(0, 1, (N, 6))
Y = np.sin(X.sum(axis=1)) + np.random.normal(0, 0.1*N, N) # Gaussian noise wiht zero mean and variance 0.1

In [3]:
from CRR import ConformalNearestNeighboursRegressor
M = 4
cp = ConformalNearestNeighboursRegressor(3)
cp.learn_initial_training_set(X[:M], Y[:M])

In [4]:
cp.D.shape

(4, 4)

In [5]:
x = X[M]
y = Y[M]
cp.learn_one(x, y)
cp.D

array([[0.        , 0.84709765, 0.82860374, 0.77990332, 0.90988838],
       [0.84709765, 0.        , 0.78714859, 1.14685844, 0.76810604],
       [0.82860374, 0.78714859, 0.        , 0.86290875, 0.4366131 ],
       [0.77990332, 1.14685844, 0.86290875, 0.        , 0.99772932],
       [0.90988838, 0.76810604, 0.4366131 , 0.99772932, 0.        ]])

In [6]:
cp2 = ConformalNearestNeighboursRegressor(k=3)
cp2.learn_initial_training_set(X[:M+1], Y[:M+1])
cp2.D

array([[0.        , 0.84709765, 0.82860374, 0.77990332, 0.90988838],
       [0.84709765, 0.        , 0.78714859, 1.14685844, 0.76810604],
       [0.82860374, 0.78714859, 0.        , 0.86290875, 0.4366131 ],
       [0.77990332, 1.14685844, 0.86290875, 0.        , 0.99772932],
       [0.90988838, 0.76810604, 0.4366131 , 0.99772932, 0.        ]])

In [7]:
np.allclose(cp.D, cp2.D)

True

In [8]:
cp.D

array([[0.        , 0.84709765, 0.82860374, 0.77990332, 0.90988838],
       [0.84709765, 0.        , 0.78714859, 1.14685844, 0.76810604],
       [0.82860374, 0.78714859, 0.        , 0.86290875, 0.4366131 ],
       [0.77990332, 1.14685844, 0.86290875, 0.        , 0.99772932],
       [0.90988838, 0.76810604, 0.4366131 , 0.99772932, 0.        ]])

In [9]:
interesting_object = cp.D.argsort(axis=0)[1:4]
interesting_object.T

array([[3, 2, 1],
       [4, 2, 0],
       [4, 1, 0],
       [0, 2, 4],
       [2, 1, 0]])

In [10]:
cp.D.shape[0]

5

In [11]:
y = cp.y[:-1]

In [12]:
np.append(y, 0)[np.array([4, 2, 0])].mean()

-121.32916562118368

In [13]:
y[np.array([2, 0])].sum()/3

-121.32916562118368

In [14]:
for i, col in enumerate(interesting_object.T): 
    print(col)
    print()
    

[3 2 1]

[4 2 0]

[4 1 0]

[0 2 4]

[2 1 0]



In [20]:
from CRR import ConformalNearestNeighboursRegressor
M = 1000
k = 20
cp = ConformalNearestNeighboursRegressor(k=k)
cp.learn_initial_training_set(X[:M], Y[:M])
x = X[M]
d = cp.distance_func(cp.X, x)
D = cp.update_distance_matrix(cp.D, d)

In [21]:
cp.predict(x)

(-184.17840874936772, 235.32658552882438)

In [22]:
Y[M]

42.10928423984113