In [14]:
import numpy as np
import matplotlib.pyplot as plt

N = 100
np.random.seed(1)
X = np.random.uniform(0, 2*np.pi, (N,4))
y = np.sin(X[:,0] + X[:,1]) + np.random.normal(0, 0.1, N) 

In [15]:
def kernel(x_i,x_j):
    # return np.dot(x_j,x_i) # Linear Kernel, same as not using Kernels at all
    # return np.dot(x_j,x_i)**2 # Polynomial Kernel
    return np.exp(-0.5*np.linalg.norm(x_i-x_j)) # Gaussian Kernel

# We could just call the kernel function every time
# Instead we store the solutions in this matrix
# to save some computations
K = np.zeros((X.shape[0],X.shape[0]))
for i, row in enumerate(K):
    for j, col in enumerate(K.T):
        K[i,j]=kernel(X[i,:],X[j,:])

In [16]:
from kernels import RBF
ker = RBF(1)
K2 = ker(X)

In [17]:
K

array([[1.        , 0.10751204, 0.15360609, ..., 0.11719949, 0.03496241,
        0.16899852],
       [0.10751204, 1.        , 0.12699465, ..., 0.14158969, 0.12416919,
        0.08246242],
       [0.15360609, 0.12699465, 1.        , ..., 0.27152396, 0.16599782,
        0.42531818],
       ...,
       [0.11719949, 0.14158969, 0.27152396, ..., 1.        , 0.1254418 ,
        0.16950826],
       [0.03496241, 0.12416919, 0.16599782, ..., 0.1254418 , 1.        ,
        0.08308055],
       [0.16899852, 0.08246242, 0.42531818, ..., 0.16950826, 0.08308055,
        1.        ]])

In [18]:
K2

array([[1.00000000e+00, 4.78633783e-05, 8.94734219e-04, ...,
        1.01807857e-04, 1.70603269e-10, 1.79704777e-03],
       [4.78633783e-05, 1.00000000e+00, 2.00043649e-04, ...,
        4.79552451e-04, 1.65968664e-04, 3.90142590e-06],
       [8.94734219e-04, 2.00043649e-04, 1.00000000e+00, ...,
        3.33968789e-02, 1.58106578e-03, 2.31825896e-01],
       ...,
       [1.01807857e-04, 4.79552451e-04, 3.33968789e-02, ...,
        1.00000000e+00, 1.80671053e-04, 1.83591754e-03],
       [1.70603269e-10, 1.65968664e-04, 1.58106578e-03, ...,
        1.80671053e-04, 1.00000000e+00, 4.20289173e-06],
       [1.79704777e-03, 3.90142590e-06, 2.31825896e-01, ...,
        1.83591754e-03, 4.20289173e-06, 1.00000000e+00]])

In [19]:
np.atleast_2d(X[0,:])

array([[2.62022653e+00, 4.52593227e+00, 7.18638172e-04, 1.89961158e+00]])

In [20]:
k = ker(X, np.array([0.2, 0.8, 0.3, 0.1])).reshape(-1,1)

In [21]:
x = np.array([0.2, 0.8, 0.3, 0.1])
kappa = ker(x,x)

In [22]:
np.block([[K, k], [k.T, kappa]])

array([[1.00000000e+00, 1.07512039e-01, 1.53606092e-01, ...,
        3.49624099e-02, 1.68998523e-01, 9.79029008e-06],
       [1.07512039e-01, 1.00000000e+00, 1.26994652e-01, ...,
        1.24169191e-01, 8.24624173e-02, 6.02912392e-02],
       [1.53606092e-01, 1.26994652e-01, 1.00000000e+00, ...,
        1.65997819e-01, 4.25318182e-01, 2.41923404e-08],
       ...,
       [3.49624099e-02, 1.24169191e-01, 1.65997819e-01, ...,
        1.00000000e+00, 8.30805458e-02, 7.61337035e-10],
       [1.68998523e-01, 8.24624173e-02, 4.25318182e-01, ...,
        8.30805458e-02, 1.00000000e+00, 2.68177366e-09],
       [9.79029008e-06, 6.02912392e-02, 2.41923404e-08, ...,
        7.61337035e-10, 2.68177366e-09, 1.00000000e+00]])

In [27]:
from CRR import KernelConformalRidgeRegressor
from kernels import RBF

kernel = RBF(1)

cp = KernelConformalRidgeRegressor(a=1, kernel=kernel)
for i, (obj, lab) in enumerate(zip(X, y)):
    cp.predict(x, epsilon=0.1)
    cp.learn_one(obj, lab)

In [28]:
np.allclose(cp.Kinv @ cp.K, np.identity(cp.K.shape[0]))

False